# -*- coding: utf-8 -*-
"""
style_feature_importance.py

Analyzes how relevant each individual feature from your StyleExtractor is
for fake/real classification, instead of evaluating the whole branch.

Flow:
1. Loads the .pkl generated by StyleExtractor.save_features_pkl()
   (must contain X, feature_names, y).
2. Trains a simple model (RandomForest) ONLY with the style features.
3. Computes:
   - Permutation importance (robust, model-agnostic)
   - SHAP values (if the library is available)
   - Correlation matrix between features (to detect redundancy,
     e.g. ttr / redundancy / herdans_c / root_ttr measuring the same thing)
4. Exports a CSV with the ranking and a correlation heatmap.

Usage:
    python style_feature_importance.py --pkl path/to/style_features.pkl --out ./results

Requirements:
    pip install scikit-learn pandas numpy matplotlib seaborn shap
    (shap is optional; if not installed, the script still works
    with permutation importance alone)
"""

from __future__ import annotations

import argparse
import pickle
from pathlib import Path

import numpy as np
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split, StratifiedKFold, cross_val_score
from sklearn.inspection import permutation_importance
from sklearn.metrics import classification_report, roc_auc_score

try:
    import shap  # type: ignore
    HAS_SHAP = True
except Exception:
    HAS_SHAP = False

try:
    import matplotlib.pyplot as plt
    import seaborn as sns
    HAS_PLOTTING = True
except Exception:
    HAS_PLOTTING = False


def load_pkl(pkl_path: str):
    with open(pkl_path, "rb") as f:
        payload = pickle.load(f)

    X = payload["X"]
    feature_names = payload["feature_names"]
    y = payload.get("y")

    if y is None:
        raise ValueError(
            "The .pkl doesn't have 'y' (labels). Regenerate it with "
            "save_features_pkl(..., labels=your_labels)."
        )

    y = np.array(y)
    X = np.array(X)
    return X, np.array(feature_names), y


def train_baseline_model(X_train, y_train):
    """Simple RandomForest: fast, doesn't require scaling, and is a good
    model-agnostic baseline for measuring importance."""
    clf = RandomForestClassifier(
        n_estimators=300,
        max_depth=None,
        min_samples_leaf=2,
        class_weight="balanced",
        n_jobs=-1,
        random_state=42,
    )
    clf.fit(X_train, y_train)
    return clf


def run_cross_validation(X, y, n_splits=5):
    """AUC on stratified CV, to know if the style branch on its own has
    real predictive power before going down to feature level."""
    clf = RandomForestClassifier(
        n_estimators=300, class_weight="balanced", n_jobs=-1, random_state=42
    )
    skf = StratifiedKFold(n_splits=n_splits, shuffle=True, random_state=42)
    scores = cross_val_score(clf, X, y, cv=skf, scoring="roc_auc")
    return scores


def compute_permutation_importance(clf, X_test, y_test, feature_names, n_repeats=30):
    result = permutation_importance(
        clf, X_test, y_test,
        n_repeats=n_repeats,
        random_state=42,
        scoring="roc_auc",
        n_jobs=-1,
    )
    df = pd.DataFrame({
        "feature": feature_names,
        "importance_mean": result.importances_mean,
        "importance_std": result.importances_std,
    }).sort_values("importance_mean", ascending=False)
    return df


def compute_shap_importance(clf, X_test, feature_names, sample_size=200):
    if not HAS_SHAP:
        print("[SHAP] library not available, skipping this step "
              "(pip install shap to enable it).")
        return None

    if len(X_test) > sample_size:
        idx = np.random.RandomState(42).choice(len(X_test), sample_size, replace=False)
        X_sample = X_test[idx]
    else:
        X_sample = X_test

    explainer = shap.TreeExplainer(clf)
    shap_values = explainer.shap_values(X_sample)

    # For binary classification, shap_values can come as a list [class0, class1]
    if isinstance(shap_values, list):
        shap_values = shap_values[1]

    mean_abs_shap = np.abs(shap_values).mean(axis=0)
    df = pd.DataFrame({
        "feature": feature_names,
        "mean_abs_shap": mean_abs_shap,
    }).sort_values("mean_abs_shap", ascending=False)
    return df


def compute_correlation_matrix(X, feature_names):
    df = pd.DataFrame(X, columns=feature_names)
    corr = df.corr(method="spearman")
    return corr


def find_redundant_pairs(corr: pd.DataFrame, threshold: float = 0.85):
    """Detects pairs of highly correlated features: candidates to remove
    or merge (e.g. ttr / redundancy / herdans_c / root_ttr)."""
    pairs = []
    cols = corr.columns
    for i in range(len(cols)):
        for j in range(i + 1, len(cols)):
            val = corr.iloc[i, j]
            if abs(val) >= threshold:
                pairs.append((cols[i], cols[j], round(float(val), 3)))
    pairs.sort(key=lambda x: -abs(x[2]))
    return pairs


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--pkl", required=True, help="Path to the StyleExtractor .pkl")
    parser.add_argument("--out", default="./style_importance_results", help="Output folder")
    parser.add_argument("--test-size", type=float, default=0.25)
    parser.add_argument("--corr-threshold", type=float, default=0.85)
    args = parser.parse_args()

    out_dir = Path(args.out)
    out_dir.mkdir(parents=True, exist_ok=True)

    print(f"[1/6] Loading {args.pkl} ...")
    X, feature_names, y = load_pkl(args.pkl)
    print(f"      X shape={X.shape}, features={len(feature_names)}, "
          f"classes={np.unique(y, return_counts=True)}")

    print("[2/6] Cross-validation (AUC) of the full style branch ...")
    cv_scores = run_cross_validation(X, y)
    print(f"      AUC per fold: {np.round(cv_scores, 3)}")
    print(f"      Mean AUC: {cv_scores.mean():.3f} (+/- {cv_scores.std():.3f})")
    if cv_scores.mean() < 0.55:
        print("      -> AUC close to 0.5: the style branch, as it stands, "
              "contributes little discriminative power on its own.")

    print("[3/6] Training baseline model (train/test split) ...")
    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=args.test_size, stratify=y, random_state=42
    )
    clf = train_baseline_model(X_train, y_train)
    y_pred = clf.predict(X_test)
    y_proba = clf.predict_proba(X_test)[:, 1]
    print(classification_report(y_test, y_pred))
    print(f"      Test AUC: {roc_auc_score(y_test, y_proba):.3f}")

    print("[4/6] Permutation importance ...")
    perm_df = compute_permutation_importance(clf, X_test, y_test, feature_names)
    perm_path = out_dir / "permutation_importance.csv"
    perm_df.to_csv(perm_path, index=False)
    print(f"      Saved to {perm_path}")
    print(perm_df.head(15).to_string(index=False))

    print("[5/6] SHAP importance (if available) ...")
    shap_df = compute_shap_importance(clf, X_test, feature_names)
    if shap_df is not None:
        shap_path = out_dir / "shap_importance.csv"
        shap_df.to_csv(shap_path, index=False)
        print(f"      Saved to {shap_path}")
        print(shap_df.head(15).to_string(index=False))

    print("[6/6] Correlation matrix and redundant features ...")
    corr = compute_correlation_matrix(X, feature_names)
    corr_path = out_dir / "correlation_matrix.csv"
    corr.to_csv(corr_path)

    redundant = find_redundant_pairs(corr, threshold=args.corr_threshold)
    redundant_path = out_dir / "redundant_pairs.csv"
    pd.DataFrame(redundant, columns=["feature_a", "feature_b", "spearman_corr"]).to_csv(
        redundant_path, index=False
    )
    print(f"      {len(redundant)} pairs with |corr| >= {args.corr_threshold} "
          f"saved to {redundant_path}")
    for a, b, v in redundant[:15]:
        print(f"      {a}  <->  {b}   corr={v}")

    if HAS_PLOTTING:
        plt.figure(figsize=(14, 12))
        sns.heatmap(corr, cmap="coolwarm", center=0, square=True,
                    xticklabels=True, yticklabels=True)
        plt.title("Correlation (Spearman) between style features")
        plt.tight_layout()
        heatmap_path = out_dir / "correlation_heatmap.png"
        plt.savefig(heatmap_path, dpi=150)
        print(f"      Heatmap saved to {heatmap_path}")
    else:
        print("      [plot] matplotlib/seaborn not available, skipping the heatmap.")

    print("\nDone. Check the folder:", out_dir.resolve())
    print("Reading suggestions:")
    print(" - If the CV AUC is low (~0.5-0.55), the problem is signal, not just fusion.")
    print(" - If there are many redundant pairs, remove/merge before adding new features.")
    print(" - Cross-reference permutation_importance.csv with shap_importance.csv: features")
    print("   ranked low in both are the first candidates to cut.")


if __name__ == "__main__":
    main()
