# -*- coding: utf-8 -*-
"""
style_feature_importance.py

Analyzes how relevant each individual feature from your StyleExtractor is
for fake/real classification, instead of evaluating the whole branch.

Flow:
1. Loads the .pkl generated by StyleExtractor.save_features_pkl()
   (must contain X, feature_names, y).
2. Trains a simple model (RandomForest) ONLY with the style features.
3. Computes:
   - Permutation importance (robust, model-agnostic)
   - SHAP values (if the library is available)
   - Correlation matrix between features (to detect redundancy,
     e.g. ttr / redundancy / herdans_c / root_ttr measuring the same thing)
4. Exports a CSV with the ranking and a correlation heatmap.

Usage:
    python style_feature_importance.py --pkl path/to/style_features.pkl --out ./results

Standard-split mode (the protocol used in the thesis/article): fit on the
train split, measure permutation importance on the test split with macro-F1
(the primary metric) and ROC-AUC, averaged over several RandomForest seeds,
both per feature and per feature group (groups A-G of the style vector,
permuted jointly so correlated features don't split their importance):
    python scripts/style_feature_importance.py \
        --train-pkl data/03_features_raw/style/train_style.pkl \
        --eval-pkl data/03_features_raw/style/test_style.pkl \
        --train-xlsx data/raw/train.xlsx --eval-xlsx data/raw/test.xlsx \
        --out style_importance_results/standard_split
The optional --train-xlsx/--eval-xlsx add a length control: lexical-diversity
indices depend on text length, so it reports how much of their contribution a
plain log word-count feature recovers.

Requirements:
    pip install scikit-learn pandas numpy matplotlib seaborn shap
    (shap is optional; if not installed, the script still works
    with permutation importance alone)
"""

from __future__ import annotations

import argparse
import pickle
from pathlib import Path

import numpy as np
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split, StratifiedKFold, cross_val_score
from sklearn.inspection import permutation_importance
from sklearn.metrics import classification_report, f1_score, roc_auc_score

try:
    import shap  # type: ignore
    HAS_SHAP = True
except Exception:
    HAS_SHAP = False

try:
    import matplotlib.pyplot as plt
    import seaborn as sns
    HAS_PLOTTING = True
except Exception:
    HAS_PLOTTING = False


def load_pkl(pkl_path: str):
    with open(pkl_path, "rb") as f:
        payload = pickle.load(f)

    X = payload["X"]
    feature_names = payload["feature_names"]
    y = payload.get("y")

    if y is None:
        raise ValueError(
            "The .pkl doesn't have 'y' (labels). Regenerate it with "
            "save_features_pkl(..., labels=your_labels)."
        )

    y = np.array(y)
    X = np.array(X)
    return X, np.array(feature_names), y


def train_baseline_model(X_train, y_train):
    """Simple RandomForest: fast, doesn't require scaling, and is a good
    model-agnostic baseline for measuring importance."""
    clf = RandomForestClassifier(
        n_estimators=300,
        max_depth=None,
        min_samples_leaf=2,
        class_weight="balanced",
        n_jobs=-1,
        random_state=42,
    )
    clf.fit(X_train, y_train)
    return clf


def run_cross_validation(X, y, n_splits=5):
    """AUC on stratified CV, to know if the style branch on its own has
    real predictive power before going down to feature level."""
    clf = RandomForestClassifier(
        n_estimators=300, class_weight="balanced", n_jobs=-1, random_state=42
    )
    skf = StratifiedKFold(n_splits=n_splits, shuffle=True, random_state=42)
    scores = cross_val_score(clf, X, y, cv=skf, scoring="roc_auc")
    return scores


def compute_permutation_importance(clf, X_test, y_test, feature_names, n_repeats=30):
    result = permutation_importance(
        clf, X_test, y_test,
        n_repeats=n_repeats,
        random_state=42,
        scoring="roc_auc",
        n_jobs=-1,
    )
    df = pd.DataFrame({
        "feature": feature_names,
        "importance_mean": result.importances_mean,
        "importance_std": result.importances_std,
    }).sort_values("importance_mean", ascending=False)
    return df


def compute_shap_importance(clf, X_test, feature_names, sample_size=200):
    if not HAS_SHAP:
        print("[SHAP] library not available, skipping this step "
              "(pip install shap to enable it).")
        return None

    if len(X_test) > sample_size:
        idx = np.random.RandomState(42).choice(len(X_test), sample_size, replace=False)
        X_sample = X_test[idx]
    else:
        X_sample = X_test

    explainer = shap.TreeExplainer(clf)
    shap_values = explainer.shap_values(X_sample)

    # For binary classification, shap_values can come as a list [class0, class1]
    if isinstance(shap_values, list):
        shap_values = shap_values[1]

    mean_abs_shap = np.abs(shap_values).mean(axis=0)
    df = pd.DataFrame({
        "feature": feature_names,
        "mean_abs_shap": mean_abs_shap,
    }).sort_values("mean_abs_shap", ascending=False)
    return df


# Groups A-G of the style vector (thesis, Section "Vector de estilo").
FEATURE_GROUPS = {
    "A_readability": ["ifsz"],
    "B_formality": ["formality_f"],
    "C_syntax": ["len_sent", "sconj_per_sent", "avg_dep_depth", "verbs_per_sent"],
    "D_lexical_diversity": ["ttr", "redundancy", "herdans_c", "root_ttr"],
    "E_pos_distribution": ["pos_noun_ratio", "pos_verb_ratio", "pos_adj_ratio", "pos_adv_ratio",
                           "pos_pron_ratio", "pos_det_ratio", "pos_adp_ratio"],
    "F_spelling": ["error_rate"],
    "G_surface_signals": None,  # every remaining sig_* feature
}


def resolve_groups(feature_names):
    names = list(feature_names)
    groups = {}
    for g, members in FEATURE_GROUPS.items():
        if members is None:
            members = [n for n in names if n.startswith("sig_")]
        groups[g] = [names.index(m) for m in members if m in names]
    covered = sorted(i for idx in groups.values() for i in idx)
    if covered != list(range(len(names))):
        missing = [names[i] for i in range(len(names)) if i not in covered]
        raise ValueError(f"Features not assigned to any group: {missing}")
    return groups


def scores_for(clf, X, y, pos_label):
    pred = clf.predict(X)
    proba = clf.predict_proba(X)[:, list(clf.classes_).index(pos_label)]
    return f1_score(y, pred, average="macro"), roc_auc_score(y == pos_label, proba)


def grouped_permutation_importance(clf, X, y, groups, pos_label, n_repeats, seed):
    """Drop in test macro-F1 / ROC-AUC when all columns of a group are
    permuted together (same row permutation for every column in the group)."""
    rng = np.random.RandomState(seed)
    base_f1, base_auc = scores_for(clf, X, y, pos_label)
    out = {}
    for g, idx in groups.items():
        drops_f1, drops_auc = [], []
        for _ in range(n_repeats):
            Xp = X.copy()
            Xp[:, idx] = X[rng.permutation(len(X))][:, idx]
            f1, auc = scores_for(clf, Xp, y, pos_label)
            drops_f1.append(base_f1 - f1)
            drops_auc.append(base_auc - auc)
        out[g] = (np.mean(drops_f1), np.mean(drops_auc))
    return out


def log_word_count(xlsx_path, ids):
    """log(1 + words in headline + body), aligned to the PKL's row order."""
    raw = pd.read_excel(xlsx_path)
    if [str(i) for i in raw["Id"]] != [str(i) for i in ids]:
        raise ValueError(f"{xlsx_path} rows are not aligned with the PKL ids.")
    text = raw["Headline"].fillna("").astype(str) + " " + raw["Text"].fillna("").astype(str)
    return np.log1p(text.str.split().str.len().to_numpy(dtype=float))


def length_control(args, X_tr, y_tr, X_te, y_te, names, groups, seeds, out_dir):
    """Lexical-diversity indices depend on text length, so check how much of
    group D's contribution a plain length feature recovers."""
    with open(args.train_pkl, "rb") as f:
        len_tr = log_word_count(args.train_xlsx, pickle.load(f)["ids"])
    with open(args.eval_pkl, "rb") as f:
        len_te = log_word_count(args.eval_xlsx, pickle.load(f)["ids"])
    fake_tr, fake_te = y_tr == args.pos_label, y_te == args.pos_label
    print(f"Median words (eval): Fake={np.median(np.expm1(len_te[fake_te])):.0f}, "
          f"True={np.median(np.expm1(len_te[~fake_te])):.0f}; "
          f"ROC-AUC of length alone (shorter = Fake)={roc_auc_score(fake_te, -len_te):.3f}")

    no_d = [i for i in range(len(names)) if i not in groups["D_lexical_diversity"]]
    variants = {
        "all_style": (X_tr, X_te),
        "style_without_D": (X_tr[:, no_d], X_te[:, no_d]),
        "style_without_D_plus_length": (np.column_stack([X_tr[:, no_d], len_tr]),
                                        np.column_stack([X_te[:, no_d], len_te])),
        "length_only": (len_tr[:, None], len_te[:, None]),
    }
    rows = []
    for name, (A, B) in variants.items():
        f1s = [f1_score(y_te, RandomForestClassifier(
                   n_estimators=300, min_samples_leaf=2, class_weight="balanced",
                   n_jobs=-1, random_state=seed).fit(A, y_tr).predict(B), average="macro")
               for seed in seeds]
        rows.append({"variant": name, "macro_f1_mean": np.mean(f1s), "macro_f1_sd": np.std(f1s)})
    df = pd.DataFrame(rows)
    df.to_csv(out_dir / "length_control.csv", index=False)
    print(df.to_string(index=False))


def run_standard_split(args, out_dir):
    """Fit on the train split, evaluate on the held-out test split, averaging
    over several RandomForest seeds."""
    X_tr, names, y_tr = load_pkl(args.train_pkl)
    X_te, names_te, y_te = load_pkl(args.eval_pkl)
    if list(names) != list(names_te):
        raise ValueError("Train and eval PKLs have different feature_names.")
    pos_label = args.pos_label
    groups = resolve_groups(names)
    seeds = list(range(args.n_seeds))
    print(f"Train {X_tr.shape}, eval {X_te.shape}, seeds={seeds}, positive class={pos_label!r}")

    base, feat_f1, feat_auc, grp = [], [], [], []
    for seed in seeds:
        clf = RandomForestClassifier(
            n_estimators=300, min_samples_leaf=2, class_weight="balanced",
            n_jobs=-1, random_state=seed,
        ).fit(X_tr, y_tr)
        base.append(scores_for(clf, X_te, y_te, pos_label))
        for scoring, store in (("f1_macro", feat_f1), ("roc_auc", feat_auc)):
            r = permutation_importance(clf, X_te, y_te, n_repeats=args.n_repeats,
                                       random_state=seed, scoring=scoring, n_jobs=-1)
            store.append(r.importances_mean)
        grp.append(grouped_permutation_importance(clf, X_te, y_te, groups, pos_label,
                                                  args.n_repeats, seed))
        print(f"  seed {seed}: test macro-F1={base[-1][0]:.3f}, ROC-AUC={base[-1][1]:.3f}")

    base = np.array(base)
    pd.DataFrame(base, columns=["macro_f1", "roc_auc"]).assign(seed=seeds).to_csv(
        out_dir / "baseline_scores.csv", index=False)
    print(f"Mean test macro-F1={base[:, 0].mean():.3f} (sd {base[:, 0].std():.3f}), "
          f"ROC-AUC={base[:, 1].mean():.3f} (sd {base[:, 1].std():.3f})")

    group_of = {names[i]: g for g, idx in groups.items() for i in idx}
    feat_f1, feat_auc = np.array(feat_f1), np.array(feat_auc)
    feat_df = pd.DataFrame({
        "feature": names,
        "group": [group_of[n] for n in names],
        "f1_drop_mean": feat_f1.mean(axis=0),
        "f1_drop_sd_seeds": feat_f1.std(axis=0),
        "auc_drop_mean": feat_auc.mean(axis=0),
        "auc_drop_sd_seeds": feat_auc.std(axis=0),
    }).sort_values("f1_drop_mean", ascending=False)
    feat_df.to_csv(out_dir / "permutation_importance.csv", index=False)
    print(feat_df.head(15).to_string(index=False))

    grp_df = pd.DataFrame([
        {"group": g, "n_features": len(groups[g]),
         "f1_drop_mean": np.mean([r[g][0] for r in grp]),
         "f1_drop_sd_seeds": np.std([r[g][0] for r in grp]),
         "auc_drop_mean": np.mean([r[g][1] for r in grp]),
         "auc_drop_sd_seeds": np.std([r[g][1] for r in grp])}
        for g in groups
    ]).sort_values("f1_drop_mean", ascending=False)
    grp_df.to_csv(out_dir / "group_permutation_importance.csv", index=False)
    print(grp_df.to_string(index=False))

    if args.train_xlsx and args.eval_xlsx:
        length_control(args, X_tr, y_tr, X_te, y_te, names, groups, seeds, out_dir)

    corr = compute_correlation_matrix(X_tr, names)
    corr.to_csv(out_dir / "correlation_matrix.csv")
    redundant = find_redundant_pairs(corr, threshold=args.corr_threshold)
    pd.DataFrame(redundant, columns=["feature_a", "feature_b", "spearman_corr"]).to_csv(
        out_dir / "redundant_pairs.csv", index=False)
    print(f"{len(redundant)} pairs with |corr| >= {args.corr_threshold} (train split):")
    for a, b, v in redundant:
        print(f"  {a} <-> {b}  corr={v}")
    print("\nDone. Check the folder:", out_dir.resolve())


def compute_correlation_matrix(X, feature_names):
    df = pd.DataFrame(X, columns=feature_names)
    corr = df.corr(method="spearman")
    return corr


def find_redundant_pairs(corr: pd.DataFrame, threshold: float = 0.85):
    """Detects pairs of highly correlated features: candidates to remove
    or merge (e.g. ttr / redundancy / herdans_c / root_ttr)."""
    pairs = []
    cols = corr.columns
    for i in range(len(cols)):
        for j in range(i + 1, len(cols)):
            val = corr.iloc[i, j]
            if abs(val) >= threshold:
                pairs.append((cols[i], cols[j], round(float(val), 3)))
    pairs.sort(key=lambda x: -abs(x[2]))
    return pairs


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--pkl", help="Path to the StyleExtractor .pkl (random holdout mode)")
    parser.add_argument("--train-pkl", help="Train-split .pkl (standard-split mode)")
    parser.add_argument("--eval-pkl", help="Eval-split .pkl, e.g. test (standard-split mode)")
    parser.add_argument("--out", default="./style_importance_results", help="Output folder")
    parser.add_argument("--test-size", type=float, default=0.25)
    parser.add_argument("--corr-threshold", type=float, default=0.85)
    parser.add_argument("--n-seeds", type=int, default=5)
    parser.add_argument("--n-repeats", type=int, default=30)
    parser.add_argument("--pos-label", default="Fake")
    parser.add_argument("--train-xlsx", help="Raw train .xlsx, enables the length control")
    parser.add_argument("--eval-xlsx", help="Raw eval .xlsx, enables the length control")
    args = parser.parse_args()

    out_dir = Path(args.out)
    out_dir.mkdir(parents=True, exist_ok=True)

    if args.train_pkl or args.eval_pkl:
        if not (args.train_pkl and args.eval_pkl):
            parser.error("--train-pkl and --eval-pkl must be given together")
        run_standard_split(args, out_dir)
        return
    if not args.pkl:
        parser.error("give --pkl, or --train-pkl and --eval-pkl")

    print(f"[1/6] Loading {args.pkl} ...")
    X, feature_names, y = load_pkl(args.pkl)
    print(f"      X shape={X.shape}, features={len(feature_names)}, "
          f"classes={np.unique(y, return_counts=True)}")

    print("[2/6] Cross-validation (AUC) of the full style branch ...")
    cv_scores = run_cross_validation(X, y)
    print(f"      AUC per fold: {np.round(cv_scores, 3)}")
    print(f"      Mean AUC: {cv_scores.mean():.3f} (+/- {cv_scores.std():.3f})")
    if cv_scores.mean() < 0.55:
        print("      -> AUC close to 0.5: the style branch, as it stands, "
              "contributes little discriminative power on its own.")

    print("[3/6] Training baseline model (train/test split) ...")
    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=args.test_size, stratify=y, random_state=42
    )
    clf = train_baseline_model(X_train, y_train)
    y_pred = clf.predict(X_test)
    y_proba = clf.predict_proba(X_test)[:, 1]
    print(classification_report(y_test, y_pred))
    print(f"      Test AUC: {roc_auc_score(y_test, y_proba):.3f}")

    print("[4/6] Permutation importance ...")
    perm_df = compute_permutation_importance(clf, X_test, y_test, feature_names)
    perm_path = out_dir / "permutation_importance.csv"
    perm_df.to_csv(perm_path, index=False)
    print(f"      Saved to {perm_path}")
    print(perm_df.head(15).to_string(index=False))

    print("[5/6] SHAP importance (if available) ...")
    shap_df = compute_shap_importance(clf, X_test, feature_names)
    if shap_df is not None:
        shap_path = out_dir / "shap_importance.csv"
        shap_df.to_csv(shap_path, index=False)
        print(f"      Saved to {shap_path}")
        print(shap_df.head(15).to_string(index=False))

    print("[6/6] Correlation matrix and redundant features ...")
    corr = compute_correlation_matrix(X, feature_names)
    corr_path = out_dir / "correlation_matrix.csv"
    corr.to_csv(corr_path)

    redundant = find_redundant_pairs(corr, threshold=args.corr_threshold)
    redundant_path = out_dir / "redundant_pairs.csv"
    pd.DataFrame(redundant, columns=["feature_a", "feature_b", "spearman_corr"]).to_csv(
        redundant_path, index=False
    )
    print(f"      {len(redundant)} pairs with |corr| >= {args.corr_threshold} "
          f"saved to {redundant_path}")
    for a, b, v in redundant[:15]:
        print(f"      {a}  <->  {b}   corr={v}")

    if HAS_PLOTTING:
        plt.figure(figsize=(14, 12))
        sns.heatmap(corr, cmap="coolwarm", center=0, square=True,
                    xticklabels=True, yticklabels=True)
        plt.title("Correlation (Spearman) between style features")
        plt.tight_layout()
        heatmap_path = out_dir / "correlation_heatmap.png"
        plt.savefig(heatmap_path, dpi=150)
        print(f"      Heatmap saved to {heatmap_path}")
    else:
        print("      [plot] matplotlib/seaborn not available, skipping the heatmap.")

    print("\nDone. Check the folder:", out_dir.resolve())
    print("Reading suggestions:")
    print(" - If the CV AUC is low (~0.5-0.55), the problem is signal, not just fusion.")
    print(" - If there are many redundant pairs, remove/merge before adding new features.")
    print(" - Cross-reference permutation_importance.csv with shap_importance.csv: features")
    print("   ranked low in both are the first candidates to cut.")


if __name__ == "__main__":
    main()
